/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/any/v1/divisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * find divisions
         * @description Get a list of all divisions
         */
        get: operations["AnyFindDivisions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/any/v1/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * find tags
         * @description Get a list of all tags
         */
        get: operations["AnyFindTags"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/any/v1/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * find roles
         * @description Get a list of all roles
         */
        get: operations["AnyFindRoles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/any/v1/alive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * healthcheck
         * @description Healthcheck endpoint
         */
        get: operations["AnyGetAlive"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mailinglists/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** find mailinglist users */
        get: operations["MlFindUsers"];
        /**
         * create or update mailinglist user
         * @description Create or update mailinglist-user
         */
        put: operations["MlUpsertUser"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mailinglists/v1/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** get mailinglist user */
        get: operations["MlGetUser"];
        put?: never;
        post?: never;
        /** delete mailinglist user */
        delete: operations["MlDeleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mailinglists/v1/users/sherpa-id/{sherpaId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** get mailinglist user by sherpa id */
        get: operations["MlGetUserBySherpaId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mailinglists/v1/divisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** find divisions */
        get: operations["MlFindDivisions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mailinglists/v1/divisions/{divisionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** get division */
        get: operations["MlGetDivision"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mailinglists/v1/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * find subscriptions
         * @description Get subscriptions of users to mailinglists. At least one filter parameter is required but not all. When given user id or list id does not exist, an empty array is returned.
         */
        get: operations["MlFindSubscriptions"];
        /**
         * add subscription
         * @description Subscribe a user to a mailinglist, who is not assigned by a sherpa distributor. A subscription cannot be updated with this endpoint. Even though the combination of list id and user id would be assumed as unique, sending a request with a (listId, userId) and a different email will not update the subscription but insert a new one.
         */
        put: operations["MlAddSubscription"];
        post?: never;
        /**
         * delete subscriptions
         * @description Unsubscribe users from mailinglists matching the query parameters
         */
        delete: operations["MlDeleteSubscriptions"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mailinglists/v1/unsubscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * find unsubscriptions
         * @description Get a list of Unsubscriptions of a List
         */
        get: operations["MlFindUnsubscriptions"];
        /**
         * add unsubscription
         * @description Unsubscribe an email from a List
         */
        put: operations["MlAddUnsubscription"];
        post?: never;
        /**
         * delete unsubscription
         * @description Delete an single mailinglist unsubscription by mailing list id and email
         */
        delete: operations["MlDeleteUnsubscription"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mailinglists/v1/lists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** find mailinglists */
        get: operations["MlFindMailinglists"];
        /** create or update mailinglist */
        put: operations["MlUpsertMailinglist"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mailinglists/v1/lists/{mailinglistId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** get mailinglist */
        get: operations["MlGetMailinglist"];
        put?: never;
        post?: never;
        /** delete mailinglist */
        delete: operations["MlDeleteMailinglist"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mailinglists/v1/internal-subscribers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** find internal subscribers */
        get: operations["MlFindInternalSubscribers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mailinglists/v1/banned-emails": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * find banned emails
         * @description Get a list of emails which are NOT allowed to log in. Only implemented by Sherpa!
         */
        get: operations["MlFindBannedEmails"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/saml/party/newusers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Find new users by date
         * @description Find created users by date. Response does not include memberships or roles.
         */
        post: operations["SamlFindNewUsersByDate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/saml/party/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get users by ids
         * @description Get detailed information about users and their memberships and roles by id.
         */
        post: operations["SamlGetUsersById"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/saml/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Find users
         * @description Find and filter users. Get detailed information about the user memberships and roles.
         */
        get: operations["SamlFindUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/saml/v1/guest-accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a guest account
         * @description Creates a guest account for a person who has no access to the Grünes Netz
         *     yet, in a single call: create the party record (or reuse the matching
         *     existing one), check that the person qualifies, and set the guest marker.
         *
         *     The guest marker must carry an expiry from the start. There must be no
         *     point in time at which a guest account exists without one. How long that
         *     expiry runs is Sherpa's to decide — the marker has a default and a
         *     maximum duration — so the caller sends no duration and reads the
         *     resulting date off the returned record.
         *
         *     A person who already has access — a member, or the holder of a role that
         *     grants access without a membership — does not qualify and is rejected
         *     with `409`.
         *
         *     The returned id comes from the same sequence as regular party records. It
         *     becomes the `uidNumber` in LDAP and is the primary user id across the
         *     Grünes Netz, so it has to be in the response body.
         */
        post: operations["SamlCreateGuestAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/saml/v1/guest-accounts/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Sherpa user id of the guest account */
                userId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke a guest account
         * @description Removes the guest marker from a party record. Used to end a guest's
         *     access before its expiry, e.g. on abuse. An expired marker ends the
         *     access on its own and needs no call.
         *
         *     Removing the account in LDAP alone is not enough: the marker would stay
         *     in Sherpa and the next user sync would reactivate the guest.
         */
        delete: operations["SamlRevokeGuestAccount"];
        options?: never;
        head?: never;
        /**
         * Renew a guest account
         * @description Extends the expiry of an existing guest marker and returns the updated
         *     party record. Used while the account is still valid, e.g. for a guest
         *     who keeps helping beyond the end of a campaign.
         *
         *     Repeating the creating call is not a way to renew. While the marker
         *     holds, the person has access and no longer qualifies as a guest, so the
         *     call would be rejected with `409`. Revoking and creating again is not
         *     one either: it drops the existing role assignment along with its
         *     history, restarts the deadlines towards anonymization, and lets the
         *     maximum duration be sidestepped one default duration at a time.
         *
         *     The new expiry is Sherpa's to determine, the same way it is on creation,
         *     and is read off the returned record.
         */
        patch: operations["SamlRenewGuestAccount"];
        trace?: never;
    };
    "/gnetz/v2/profiles/ids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * get user profile ids
         * @description Get a complete list of all user profile ids
         */
        get: operations["GnGetProfileIds"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gnetz/v2/profiles/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get user profiles
         * @description Get user profiles by profile or user ids
         */
        post: operations["GnGetProfiles"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gnetz/v2/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create user profile
         * @description Create user profile
         */
        post: operations["GnCreateProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gnetz/v2/profiles/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete user profiles
         * @description Delete user profiles
         */
        post: operations["GnDeleteProfiles"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gnetz/v2/profiles/{profileId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update user profile
         * @description Update user profile
         */
        put: operations["GnUpdateProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gnetz/v2/profiles/{profileId}/form-values": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get profile form values
         * @description Get profile form values
         */
        get: operations["GnGetProfileFormValues"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gnetz/v2/divisions/{divisionKey}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * get division
         * @description Get a division by division key
         */
        get: operations["GnGetDivision"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gnetz/v2/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * find tags
         * @description Get a list of tags
         */
        get: operations["GnFindTags"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gnetz/v2/interests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * find interest tags
         * @description Get a list of tags with type `interest`
         */
        get: operations["GnFindInterests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gnetz/v2/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * find skill tags
         * @description Get a list of tags with type `skill`
         */
        get: operations["GnFindSkills"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description External Division identifier.
         *       - First digit is the index of the hierarchy
         *         1. GR
         *         2. GJ
         *         3. KPV
         *       - second and third digit is the *LV*
         *       - next three is the *KV*
         *       - last two is the *OV*
         *     All undefined hierarchy levels are nulled.
         * @example 10000000
         */
        DivisionKey: string;
        /**
         * @description The root hierarchy the Division belongs to:
         *       - `GR`: Division of the Green Party ("BÜNDNIS 90/DIE GRÜNEN")
         *       - `GJ`: Division of the Green Youth ("Grüne Jugend")
         *       - `KPV`: Local political Association ("Kommunalpolitische Vereinigung"), currently not in use
         * @enum {string}
         */
        HierarchyType: "GR" | "GJ" | "KPV";
        AnyDivision: {
            /**
             * @description Global unique id. This id has no collisions with organization or user ids.
             * @example 4086
             */
            internalId: string;
            /** @example 10100101 */
            divisionKey: components["schemas"]["DivisionKey"];
            /** @example GR */
            hierarchy: components["schemas"]["HierarchyType"];
            /**
             * @example ov
             * @enum {string}
             */
            level: "bv" | "lv" | "kv" | "ov";
            /**
             * @description Bezeichnung der Gliederungsebene (Bundesverband/Landesverband/Kreisverband/Ortsverband | Abteilung | Regionalverband)
             * @example Ortsverband
             */
            name1: string;
            /**
             * @description Name der jeweiligen Abteilung. Aufgelöste Gliederungen haben den Suffix `_ALT` angefügt. Über diesen Suffix können Gliederungen gefiltert werden nach aktiv/inaktiv.
             * @example Aalen
             */
            name2: string;
            /** @example Aalen OV */
            shortName: string;
            /**
             * @description zip code of office location
             * @example 25488
             */
            officeZip: string | null;
            /**
             * @description street name of office location
             * @example Bahnhofstr.
             */
            officeStreet: string | null;
            /**
             * @description house number of office location
             * @example 13
             */
            officeHouseNumber: string | null;
            /**
             * @description city of office location
             * @example Berlin
             */
            officeCity: string | null;
            /**
             * @description the preferred email to contact the division
             * @example info@example.com
             */
            favoriteEmail: string | null;
            /**
             * @description list of internet presences
             * @example [
             *       "https://example.com/"
             *     ]
             */
            urls: string[];
            /**
             * @example [
             *       "john.doe@example.com",
             *       "jane.doe@example.com"
             *     ]
             */
            emails: string[];
            /**
             * @example {
             *       "jane.doe@example.com": "BV-GRÜNE-Info"
             *     }
             */
            emailTags: {
                [key: string]: string;
            };
            /**
             * @description purposes associated with email
             *     currently used values:
             *       - privat
             *       - grüne
             *       - dienstlich
             *       - Postanschrift
             *       - Rechnungsanschrift
             *       - Lieferanschrift
             * @example {
             *       "jane.doe@example.com": {
             *         "id": "2",
             *         "label": "grüne"
             *       }
             *     }
             */
            emailPurpose: {
                [key: string]: {
                    /** @example 12 */
                    id: string;
                    /** @example grüne */
                    label: string;
                };
            };
        };
        AnyTag: {
            /** @example 691378 */
            id: string;
            /** @example 236 */
            parentId: string | null;
            /** @example Technik Parteitag */
            name: string;
            aliases: Record<string, never>[];
        };
        AnyRole: {
            /** @example 12272402 */
            id: string;
            /**
             * @description A: Amt B: Beziehung M: Mandat R: Rolle S: System
             * @example R
             * @enum {string}
             */
            type: "A" | "B" | "M" | "R" | "S";
            /** @example LAG Regionaler Strukturwandel Mitarbeitende */
            label: string;
            /** @enum {string|null} */
            hierarchy: "gr" | "gj" | "kpv" | null;
            /**
             * @description A role can be scoped to a particular hierarchy level or for all
             * @enum {string}
             */
            level: "all" | "bv" | "lv" | "kv" | "ov" | "bezv";
            /** @example 99 */
            maxAge: number;
            /** @example 0 */
            minAge: number | null;
            categories: components["schemas"]["AnyRoleCategory"][];
            aliases: components["schemas"]["AnyRoleAlias"][];
            tags: components["schemas"]["AnyRoleTag"][];
        };
        AnyRoleCategory: {
            /** @example 308 */
            id: string;
            /** @example LAG Regionaler Strukturwandel */
            label: string;
            aliases: components["schemas"]["AnyRoleAlias"][];
        };
        AnyRoleAlias: {
            /** @example 308 */
            id: string;
            /** @example Parteirat */
            label: string;
            /** @example 8671 */
            divisionId: number;
            divisionKey: components["schemas"]["DivisionKey"];
        };
        AnyRoleTag: {
            /** @example 7023839 */
            id: string;
            /** @example 6590132 */
            tagId: string;
            /** @example eShop Rolle */
            name: string;
        };
        ServerAliveDto: {
            /** @example ServerAliveTO */
            toType?: string;
            /** @example true */
            alive?: boolean;
            /** @example Live-System (Version 1.5-24, Serverzeit 2023-12-06 17:03:15, 43 active users) */
            serverInfo?: string;
        };
        /** @description A natural person, an AMVparty in Sherpa */
        MlUser: {
            /**
             * @description Mailinglist-user id.
             * @example 12795114
             */
            id: number;
            /**
             * @description The sherpa user id
             * @example 12795004
             */
            sherpaPartyId: number | null;
            /**
             * Format: email
             * @description A user's default e-mail
             * @example user@example.org
             */
            email: string | null;
            /**
             * @description Users display name. Contains the Gnetz username
             * @example johndoe1
             */
            name: string | null;
            divisions: components["schemas"]["MlDivision"][];
        };
        MlUpsertUserDto: {
            /** @description User id. Leave empty/null to create new user. No check for duplicates */
            id?: number | null;
            /**
             * @description The sherpa user id
             * @example 12795004
             */
            sherpaPartyId?: number | null;
            /**
             * Format: email
             * @description A user's default e-mail
             * @example user@example.org
             */
            email?: string | null;
            /**
             * @description username
             * @example johndoe1
             */
            name?: string | null;
            /**
             * @description list of division ids
             * @example [
             *       10689,
             *       11326
             *     ]
             */
            divisions?: number[] | null;
        };
        /** @description A compact version of MlUser */
        MlUserItem: {
            /** @example 12795004 */
            id: number;
            /**
             * @description The sherpa user id
             * @example 1820005
             */
            sherpaPartyId: number | null;
            /**
             * Format: email
             * @description A user's default e-mail
             * @example user@example.org
             */
            email: string | null;
            /**
             * @description Display name. Contains the Gnetz username.
             * @example johndoe5
             */
            name: string | null;
            /**
             * @description list of division ids
             * @example [
             *       10689,
             *       11326
             *     ]
             */
            divisions: number[] | null;
        };
        /** @description A division (dt. Gliederung) of the party and it's associated mailing lists. */
        MlDivision: {
            /** @example 10689 */
            id: number;
            identifier: components["schemas"]["DivisionKey"];
            /**
             * @description Parent division id
             * @example 9641
             */
            parentId: number | null;
            /**
             * @description Full name of the division
             * @example Kreisverband Herne
             */
            name: string;
            /**
             * @description Contains the `shortName` of the division
             * @example Herne KV
             */
            shortDescription: string;
            hierarchy: components["schemas"]["HierarchyType"];
            /**
             * @description The level of the Division in said hierarchy, whilst not all hierarchies have all levels:
             *       - `1`: BV ("Bundesverband")
             *       - `2`: LV ("Landesverband")
             *       - `3`: BezV ("Bezirksverband"), not always used
             *       - `4`: KV ("Kreisverband")
             *       - `5`: OV ("Ortsverband")
             * @example 4
             */
            hierarchyLevel: number;
            lists: components["schemas"]["MlMailinglist"][];
            distributors: components["schemas"]["MlSherpaDistributor"][] | null;
        };
        /** @description A mailing list, as managed by Sympa/Mailman */
        MlMailinglist: {
            /** @example 12345 */
            id: number;
            /** @example Test Externe Mailinglisten */
            name: string;
            /** @example Mailingliste zum Sherpa-Verteiler \"Test Externe Mailinglisten\" */
            description: string | null;
            /** @description A user can unsubscribe itself from the list */
            isunsubscribeable: boolean;
            /** @enum {string} */
            visibility: "public" | "partymember" | "divisionmember" | "internal";
            /** @example 2084 */
            divisionId: number | null;
            /**
             * @description A static alphanumeric token, used to authenticate against the Backend to read subscriber lists
             * @example b7JETuh0tDWEXJjyKrA6wmPBeoqJW4RXOuGEhgn0JBuAlt59VkTaGr5FoN2H051T
             */
            readonly subscriberSyncToken: string;
            /**
             * @description list of sherpa distributor ids
             * @example [
             *       123,
             *       124
             *     ]
             */
            distributors: number[];
        };
        MlUpsertMailinglistDto: {
            /**
             * @description Leave empty or set to null to create a new entry
             * @example 12345
             */
            id?: number | null;
            /** @example Test Externe Mailinglisten */
            name: string;
            /** @example Mailingliste zum Sherpa-Verteiler \"Test Externe Mailinglisten\" */
            description?: string | null;
            /**
             * @description A user can unsubscribe itself from the list.
             * @default false
             */
            isunsubscribeable: boolean;
            /** @enum {string} */
            visibility: "public" | "partymember" | "divisionmember" | "internal";
            /** @example 2084 */
            divisionId?: number | null;
            /**
             * @description list of sherpa distributor ids
             * @example [
             *       123,
             *       124
             *     ]
             */
            distributors?: number[] | null;
        };
        MlSubscription: {
            /** @description mailinglist-user id (not sherpa user id) */
            user: number;
            /** @description mailing list id */
            list: number;
            /**
             * Format: email
             * @example user+list@example.org
             */
            email: string;
            /**
             * @example m
             * @enum {string|null}
             */
            userGender: "m" | "w" | "d" | null;
            /** @example Doe */
            userSurname: string | null;
            /** @example Doe */
            userPrename: string | null;
        };
        MlAddSubscriptionDto: {
            /** @description mailinglist-user id (not sherpa user id) */
            user: number;
            /** @description mailing list id */
            list: number;
            /**
             * Format: email
             * @example user@example.org
             */
            email: string;
        };
        MlUnsubscription: {
            id: number;
            list: number;
            /**
             * Format: email
             * @example user+list@example.org
             */
            email: string;
        };
        /** @description Link between Sherpa-Selektionen and Mailinglists, usually of the type "E-Mail-Verteiler (distributor)" */
        MlSherpaDistributor: {
            /** @example 9489 */
            id: number;
            /** @example Test Externe Mailinglisten */
            name: string;
        };
        /** @description User and associated email address in sherpa distributor */
        MlSherpaDistributorItem: {
            /**
             * @description sherpa user id
             * @example 14366003
             */
            sherpaPartyId: number;
            /**
             * Format: email
             * @example john.doe@example.com
             */
            email: string;
            /**
             * @example m
             * @enum {string}
             */
            userGender?: "m" | "w" | "d";
            /** @example Doe */
            userSurname?: string;
            /** @example Doe */
            userPrename?: string;
        };
        MlErrorDto: {
            /** @example ExceptionTO */
            toType: string;
            /** @example java.lang.NullPointerException */
            exceptionClassName: string;
            originalMessage: string | null;
            /** @example 500 */
            httpStatusCode: string;
            /**
             * @description Message to the user on frontend
             * @example Bei der Verarbeitung der Anfrage ist ein Fehler aufgetreten.
             */
            userMessage: string;
            stackTrace: string;
            serverInfo: string;
            requestUuid: string | null;
            /** @example server */
            source: string;
            /** @example SERVER_GENERAL */
            type: string;
            code: string | null;
        };
        SamlFindUsersResponse: {
            data: components["schemas"]["SamlUser"][];
            meta: {
                /** @description Whether a next page exists or not */
                hasNext?: boolean;
            };
        };
        /** @description new user */
        SamlNewUser: {
            /** @example SamlOnboardingPartyTO */
            toType: string;
            /**
             * @description sherpa user id
             * @example 12345678
             */
            id: string;
            /**
             * @description Firstname
             * @example John
             */
            name1: string;
            /**
             * @description Lastname
             * @example Doe
             */
            name2: string;
            /**
             * Format: email
             * @example john.doe@example.com
             */
            email: string | null;
        };
        SamlUser: {
            /** @example SamlSynchronizationPartyTO */
            toType: string;
            /**
             * @description sherpa user id
             * @example 12345678
             */
            id: string;
            ownerIdentifier: components["schemas"]["DivisionKey"];
            /** @example 11002607 */
            ownerId: string;
            /**
             * Format: date-time
             * @example 2020-07-22T13:38:30+0200
             */
            createdOn: string;
            /**
             * Format: date-time
             * @example 2022-11-25T16:45:24+0100
             */
            lastModifiedOn: string;
            /** @example John */
            name1: string;
            /** @example Doe */
            name2: string;
            /**
             * Format: email
             * @example john.doe@example.com
             */
            email: string | null;
            /** @description Sperrvermerk in sherpa. Flag to indicate that user should not receive any emails. */
            blockingNotice?: boolean;
            roles: components["schemas"]["SamlUserRole"][];
            memberships: components["schemas"]["SamlUserMembership"][];
        };
        SamlUserRole: {
            /** @example SamlSynchronizationRoleAssignmentTO */
            toType: string;
            /** @example 13926537 */
            id: string;
            ownerIdentifier: components["schemas"]["DivisionKey"];
            /** @example 7555235 */
            roleId: string;
            /**
             * @description can be a division key or an id for a non regular chapter starting with 5
             * @example 512345
             */
            delegatedByOrganizationIdentifier: string | null;
            /**
             * Format: date-time
             * @description When the assignment runs out, `null` if it does not expire. Required
             *     for the guest marker: a consumer has to be able to tell how long a
             *     guest account is still valid, both from the creating call and from
             *     the user endpoints, to warn ahead of the expiry and to prompt for a
             *     renewal.
             * @example 2026-12-31T23:59:59+0100
             */
            expiresOn: string | null;
            tags: components["schemas"]["SamlUserRoleTag"][] | null;
        };
        SamlUserRoleTag: {
            /** @example SamlGenericTagTO */
            toType: string;
            /** @example 6592657 */
            id: string;
            /** @example 6590132 */
            tagId: string;
            /** @example eShop Rolle */
            name: string;
        };
        /** @description Data collected from the invited person plus the inviting division */
        SamlCreateGuestAccountDto: {
            /**
             * @description Firstname
             * @example Jane
             */
            name1: string;
            /**
             * @description Lastname
             * @example Doe
             */
            name2: string;
            /**
             * Format: email
             * @example jane.doe@example.com
             */
            email: string;
            /**
             * Format: date
             * @example 1990-04-17
             */
            birthDate?: string;
            /**
             * @description The division the guest was invited to work in. It is picked by the
             *     inviting member and is not necessarily their own division.
             */
            ownerIdentifier: components["schemas"]["DivisionKey"];
            /**
             * @description Sherpa user id of the inviting member. Optional: the invitation is
             *     persisted in the Grüne API anyway. Useful if Sherpa should be able to
             *     tell whose invitation a guest account goes back to.
             * @example 12345678
             */
            invitedByUserId?: string | null;
        };
        SamlUserMembership: {
            /** @example SamlSynchronizationMembershipTO */
            toType: string;
            id: string;
            ownerIdentifier: components["schemas"]["DivisionKey"];
            memberOfStructureIdentifier: components["schemas"]["DivisionKey"];
        };
        SamlError: {
            /** @example ExceptionTO */
            toType?: string;
            /** @example com.proximity.gp.common.exception.InvalidCredentialsException */
            exceptionClassName?: string;
            /** @example api endpoint needs permission for SAML, caller got only GNETZ2 */
            originalMessage?: string;
            /** @example 500 */
            httpStatusCode?: string;
            /** @example Bei der Verarbeitung der Anfrage ist ein Fehler aufgetreten. */
            userMessage?: string;
            stackTrace?: string;
            /** @example Live-System (Version 1.4-89, Serverzeit 2023-04-09 09:21:47.519+0200) */
            serverInfo?: string;
            requestUuid?: string;
            /** @example server */
            source?: string;
            /** @example INVALID_CREDENTIALS */
            type?: string;
            code?: string;
        };
        GnDivisionMembership: {
            divisionKey: components["schemas"]["DivisionKey"];
            /**
             * Format: date-time
             * @example 2024-01-01T12:33:41.123Z
             */
            joinedAt: string;
            /**
             * Format: date-time
             * @example 2024-06-01T12:00:00.000Z
             */
            exitedAt: string | null;
        };
        GnProfile: {
            /**
             * Format: uuid
             * @example 9677feef-0916-4ee9-bac9-36655950666a
             */
            id: string;
            /**
             * @description the sherpa user id
             * @example 12345678
             */
            userId: string;
            /**
             * @description personal identification number
             * @example 12345678
             */
            personalId: string;
            /** @example JohnDoe1 */
            username: string;
            /** @example John */
            firstName: string;
            /** @example Doe */
            lastName: string;
            image: components["schemas"]["GnProfileImage"];
            /**
             * Format: email
             * @example john.doe@example.com
             */
            email: string;
            /**
             * Format: email
             * @description Login email of the associated gnetz account. Mirrors that account's email and, unlike `email`, is not user-editable. `null` when no gnetz account is associated.
             * @example john.doe@example.com
             */
            loginEmail: string | null;
            phoneNumbers: components["schemas"]["GnPhoneNumber"][];
            messengers: components["schemas"]["GnMessenger"][];
            socialMedia: components["schemas"]["GnSocialMedia"][];
            /**
             * @example [
             *       "101",
             *       "102"
             *     ]
             */
            tags: string[] | null;
            memberships: components["schemas"]["GnDivisionMembership"][];
            roles: components["schemas"]["GnRole"][];
            achievements: string[] | null;
            privacy: components["schemas"]["GnPrivacySettings"];
        };
        GnImageLink: {
            /**
             * @description This field is always returned by sherpa but must be left out when setting a new image for a profile.
             * @example 10
             */
            id?: string;
            /**
             * @description Image url
             * @example https://static.example.com/profiles/10b4be70-9e3d-40a5-a46a-b0668bdf7e03.jpg
             */
            url: string;
            /**
             * @description Image mimetype
             * @example image/jpeg
             */
            mimetype: string;
            /**
             * @description Width in pixels
             * @example 150
             */
            width: number;
            /**
             * @description Height in pixels
             * @example 150
             */
            height: number;
        };
        GnProfileImage: {
            thumbnail: components["schemas"]["GnImageLink"] | null;
            large: components["schemas"]["GnImageLink"] | null;
        };
        /** @enum {string} */
        GnSocialMediaType: "facebook" | "instagram" | "mastodon" | "twitter" | "chatbegruenung";
        GnSocialMedia: {
            id: string;
            /** @example twitter */
            type: components["schemas"]["GnSocialMediaType"];
            /** @example https://twitter.com/johndoe */
            url: string;
        };
        GnUpdateSocialMediaDto: {
            id?: string;
            /** @example twitter */
            type: components["schemas"]["GnSocialMediaType"];
            /** @example https://twitter.com/johndoe */
            url: string;
        };
        /** @enum {string} */
        GnMessengerType: "threema";
        GnMessenger: {
            id: string;
            /** @example threema */
            type: components["schemas"]["GnMessengerType"];
            /** @example GAvh15G12512125H */
            externalId: string;
        };
        GnUpdateMessengerDto: {
            id?: string;
            /** @example threema */
            type: components["schemas"]["GnMessengerType"];
            /** @example GAvh15G12512125H */
            externalId: string;
        };
        GnPhoneNumber: {
            id: string;
            /** @example +49 */
            country: string;
            /** @example 17712341234 */
            number: string;
        };
        GnUpdatePhoneNumberDto: {
            id?: string;
            /** @example +49 */
            country: string;
            /** @example 17712341234 */
            number: string;
        };
        /** @enum {string} */
        GnVisibility: "private" | "public" | "bv_wide" | "lv_wide" | "kv_wide" | "ov_wide";
        GnPrivacySettings: {
            /** @example public */
            overall: components["schemas"]["GnVisibility"] | null;
            /** @example public */
            email: components["schemas"]["GnVisibility"] | null;
            /** @example public */
            chatbegruenung: components["schemas"]["GnVisibility"] | null;
        };
        GnProfileFormValues: {
            emails?: string[];
            phoneNumbers?: components["schemas"]["GnPhoneNumber"][];
            messengers?: components["schemas"]["GnMessenger"][];
            socialMedia?: components["schemas"]["GnSocialMedia"][];
        };
        GnCreateProfileDto: {
            /**
             * Format: uuid
             * @description A pre-generated uuid as primary id for the new profile
             */
            id: string;
            userId: string;
            username: string;
            email: string;
            /**
             * Format: email
             * @description Login email pushed from the associated gnetz account. `null` when there is no associated login.
             */
            loginEmail?: string | null;
            privacy?: components["schemas"]["GnPrivacySettings"] | null;
        };
        GnUpdateProfileDto: {
            /** @description This field is immutable but has to be send in payload */
            userId: string;
            username: string;
            email: string;
            /**
             * Format: email
             * @description Login email pushed from the associated gnetz account. `null` when there is no associated login.
             */
            loginEmail?: string | null;
            /**
             * @description Always send the current image data on update. Marked required to
             *     prevent accidental data loss: the field can technically be omitted,
             *     but doing so loses the stored image.
             *     When adding a new image the ids must not be set.
             *     When updating a profile with unchanged image the ids must be sent along.
             */
            image: components["schemas"]["GnProfileImage"];
            phoneNumbers: components["schemas"]["GnUpdatePhoneNumberDto"][];
            messengers: components["schemas"]["GnUpdateMessengerDto"][];
            socialMedia: components["schemas"]["GnUpdateSocialMediaDto"][];
            /**
             * @example [
             *       "101",
             *       "102"
             *     ]
             */
            tags: string[];
            privacy: components["schemas"]["GnPrivacySettings"];
        };
        GnDeletedProfileDto: {
            /** @example 0de14cbe-221b-43a5-8222-45414066f5b6 */
            id: string;
            /** @example 12345678 */
            userId: string;
        };
        /** @enum {string} */
        GnTagType: "skill" | "interest";
        GnTag: {
            /** @example 1 */
            id: string;
            type: components["schemas"]["GnTagType"];
            /**
             * @description id for this tag by another system/cms
             * @example 101
             */
            externalId?: string;
            /** @example Zeitpolitik */
            tag: string;
        };
        /** @enum {string} */
        GnRoleType: "role" | "mandate" | "office";
        GnRole: {
            /**
             * @description This ID refers to the m:n relation mapping
             * @example 12345
             */
            id: string;
            /**
             * @description This ID refers to the role itself
             * @example 12345
             */
            roleId: number;
            type: components["schemas"]["GnRoleType"];
            /** @example LAG Verkehr Mitarbeitende */
            name: string;
            /** @example LAG Mobilität */
            alias: string;
        };
        GnError: {
            /**
             * @description unique error id
             * @example 17405cfc-4b50-987e
             */
            id: string;
            /**
             * Format: date-time
             * @example 2023-11-30T13:24:25.298Z
             */
            timestamp: string;
            /** @example com.proximity.gp.common.exception.InvalidCredentialsException */
            exceptionClassName: string;
            /** @example invalid request data */
            message: string;
            validationErrors: components["schemas"]["GnValidationError"][] | null;
        };
        GnValidationError: {
            /** @example division.type */
            path?: string;
            constraints?: {
                /** @example isEnum */
                type: string;
                /** @example 'foobar' is not a valid division type' */
                message: string;
            }[];
        };
    };
    responses: {
        /** @description Generic error response for authentication, validation and others */
        SamlServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["SamlError"];
            };
        };
        /** @description Not Found */
        GnNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "id": "17405cfc-4b50-987e",
                 *       "timestamp": "2023-11-30T13:24:25.298Z",
                 *       "exceptionClassName": "com.proximity.gp.common.exception.ResourceNotFoundException",
                 *       "message": "Could not find Profile with id 569f8341-087e-4c37-8c1a-ed31b246ef2a",
                 *       "validationErrors": null
                 *     }
                 */
                "application/json": components["schemas"]["GnError"];
            };
        };
        /** @description Validation failed */
        GnValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "id": "17405cfc-4b50-987e",
                 *       "timestamp": "2023-11-30T13:24:25.298Z",
                 *       "exceptionClassName": "com.proximity.gp.common.exception.ValidationException",
                 *       "message": "Invalid Request Body",
                 *       "validationErrors": [
                 *         {
                 *           "path": "division.level",
                 *           "constraints": [
                 *             {
                 *               "type": "isEnum",
                 *               "message": "'foobar' is not a valid division level"
                 *             }
                 *           ]
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["GnError"];
            };
        };
    };
    parameters: {
        /** @description User profile id */
        GnProfileId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AnyFindDivisions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of Divisions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnyDivision"][];
                };
            };
        };
    };
    AnyFindTags: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of tags */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnyTag"][];
                };
            };
        };
    };
    AnyFindRoles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of roles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnyRole"][];
                };
            };
        };
    };
    AnyGetAlive: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description healthcheck response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerAliveDto"];
                };
            };
        };
    };
    MlFindUsers: {
        parameters: {
            query: {
                /** @description Filter by division id */
                division: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of users. When a non-existing division id is sent, an empty array is returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MlUserItem"][];
                };
            };
            /** @description Division id contains non-parsable string value */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing division id */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "toType": "ExceptionTO",
                     *       "exceptionClassName": "java.lang.NullPointerException",
                     *       "originalMessage": null,
                     *       "httpStatusCode": "500",
                     *       "userMessage": "Bei der Verarbeitung der Anfrage ist ein Fehler aufgetreten.",
                     *       "stackTrace": "java.lang.NullPointerException\n\tat ...",
                     *       "serverInfo": "Live-System (Version 1.5-31, Serverzeit 2024-04-12 10:43:48, 56 active users)",
                     *       "requestUuid": null,
                     *       "source": "server",
                     *       "type": "SERVER_GENERAL",
                     *       "code": null
                     *     }
                     */
                    "application/json": components["schemas"]["MlErrorDto"];
                };
            };
        };
    };
    MlUpsertUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MlUpsertUserDto"];
            };
        };
        responses: {
            /** @description User successfully updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MlUserItem"];
                };
            };
            /** @description User successfully created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MlUserItem"];
                };
            };
            /** @description Bad Request, Not found, Internal Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MlErrorDto"];
                };
            };
        };
    };
    MlGetUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The mailinglist-user id (not sherpa user id) */
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MlUser"];
                };
            };
            /** @description Parameter id contains forbidden characters (%) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": unknown;
                };
            };
            /** @description Parameter id contains a non-parsable string value */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User with given external id does not exist */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "toType": "ExceptionTO",
                     *       "exceptionClassName": "java.lang.RuntimeException",
                     *       "originalMessage": "de.maxmomentum.extern.exception.ResourceNotFoundException: user not found (ext id 16.960.158)",
                     *       "httpStatusCode": "500",
                     *       "userMessage": "Bei der Verarbeitung der Anfrage ist ein Fehler aufgetreten.",
                     *       "stackTrace": "java.lang.RuntimeException: ...",
                     *       "serverInfo": "Live-System (Version 1.5-31, Serverzeit 2024-04-12 11:00:22, 64 active users)",
                     *       "requestUuid": null,
                     *       "source": "server",
                     *       "type": "SERVER_GENERAL",
                     *       "code": null
                     *     }
                     */
                    "application/json": components["schemas"]["MlErrorDto"];
                };
            };
        };
    };
    MlDeleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User ID */
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User id contains non-parsable string value */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User with given sherpa id does not exist */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "toType": "ExceptionTO",
                     *       "exceptionClassName": "java.lang.RuntimeException",
                     *       "originalMessage": "de.maxmomentum.extern.exception.ResourceNotFoundException: unknown user (user ext id 1.820.580.123)",
                     *       "httpStatusCode": "500",
                     *       "userMessage": "Bei der Verarbeitung der Anfrage ist ein Fehler aufgetreten.",
                     *       "stackTrace": "java.lang....",
                     *       "serverInfo": "Live-System (Version 1.5-31, Serverzeit 2024-04-12 12:09:45, 74 active users)",
                     *       "requestUuid": null,
                     *       "source": "server",
                     *       "type": "SERVER_GENERAL",
                     *       "code": null
                     *     }
                     */
                    "application/json": components["schemas"]["MlErrorDto"];
                };
            };
        };
    };
    MlGetUserBySherpaId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Sherpa User ID */
                sherpaId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MlUser"];
                };
            };
            /** @description Parameter id contains forbidden characters (%) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": unknown;
                };
            };
            /** @description Parameter id contains a non-parsable string value */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User with given sherpa id does not exist */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "toType": "ExceptionTO",
                     *       "exceptionClassName": "java.lang.RuntimeException",
                     *       "originalMessage": "de.maxmomentum.extern.exception.ResourceNotFoundException: user not found (amv pk 18.205.802)",
                     *       "httpStatusCode": "500",
                     *       "userMessage": "Bei der Verarbeitung der Anfrage ist ein Fehler aufgetreten.",
                     *       "stackTrace": "java.lang.RuntimeException: de.maxmomentum.ext",
                     *       "serverInfo": "Live-System (Version 1.5-31, Serverzeit 2024-04-12 12:01:57, 74 active users)",
                     *       "requestUuid": null,
                     *       "source": "server",
                     *       "type": "SERVER_GENERAL",
                     *       "code": null
                     *     }
                     */
                    "application/json": components["schemas"]["MlErrorDto"];
                };
            };
        };
    };
    MlFindDivisions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MlDivision"][];
                };
            };
        };
    };
    MlGetDivision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Division ID */
                divisionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MlDivision"];
                };
            };
            /** @description Parameter id contains forbidden characters (%) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": unknown;
                };
            };
            /** @description Parameter id contains a non-parsable string value */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Division with given id does not exist */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "toType": "ExceptionTO",
                     *       "exceptionClassName": "java.lang.RuntimeException",
                     *       "originalMessage": "java.lang.IllegalStateException: structure not found (pk 8.198.000)",
                     *       "httpStatusCode": "500",
                     *       "userMessage": "Bei der Verarbeitung der Anfrage ist ein Fehler aufgetreten.",
                     *       "stackTrace": "java.lang.RuntimeException: j...",
                     *       "serverInfo": "Live-System (Version 1.5-31, Serverzeit 2024-04-12 13:17:42, 50 active users)",
                     *       "requestUuid": null,
                     *       "source": "server",
                     *       "type": "SERVER_GENERAL",
                     *       "code": null
                     *     }
                     */
                    "application/json": components["schemas"]["MlErrorDto"];
                };
            };
        };
    };
    MlFindSubscriptions: {
        parameters: {
            query?: {
                /** @description Filter by mailinglist id */
                list?: string;
                /** @description Filter by mailinglist-user id (not sherpa user id) */
                user?: string;
                /** @description Filter by email. Email address has to be complete. */
                email?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description If given mailinglist id does not exist, an empty array is returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MlSubscription"][];
                };
            };
            /** @description parameter `list` contains non-parsable string */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request, Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MlErrorDto"];
                };
            };
        };
    };
    MlAddSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MlAddSubscriptionDto"];
            };
        };
        responses: {
            /** @description The User was newly subscribed to the List */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found, Unprocessable Entity, Bad Request, Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MlErrorDto"];
                };
            };
        };
    };
    MlDeleteSubscriptions: {
        parameters: {
            query?: {
                /** @description Delete subscriptions matching this user id */
                user?: string;
                /** @description Delete subscriptions matching this email */
                email?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subscriptions got deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MlFindUnsubscriptions: {
        parameters: {
            query: {
                /** @description List ID */
                list: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description If given mailinglist id does not exist, an empty array is returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MlUnsubscription"][];
                };
            };
            /** @description parameter `list` contains non-parsable string */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MlAddUnsubscription: {
        parameters: {
            query: {
                /** @description List ID */
                list: string;
                /** @description Email to unsubscribe from the List */
                email: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Okay */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MlUnsubscription"][];
                };
            };
            /** @description Parameter `list` contains non-parsable string */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found, Internal Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MlErrorDto"];
                };
            };
        };
    };
    MlDeleteUnsubscription: {
        parameters: {
            query: {
                /** @description List ID */
                list: string;
                /** @description Unsubscribed email in a List */
                email: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Okay */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MlUnsubscription"][];
                };
            };
            /** @description Unsubscription removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found, Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MlErrorDto"];
                };
            };
        };
    };
    MlFindMailinglists: {
        parameters: {
            query: {
                /** @description Filter by division id */
                division: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description If given division id does not exist, an empty array is returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MlMailinglist"][];
                };
            };
            /** @description Parameter division id contains non-parsable string */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MlUpsertMailinglist: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MlUpsertMailinglistDto"];
            };
        };
        responses: {
            /** @description Mailinglist successfully updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MlMailinglist"];
                };
            };
            /** @description Mailinglist successfully created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MlMailinglist"];
                };
            };
            /** @description Bad Request, Not found, Internal Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MlErrorDto"];
                };
            };
        };
    };
    MlGetMailinglist: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Mailinglist ID */
                mailinglistId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MlMailinglist"];
                };
            };
            /** @description Parameter id contains a non-parsable string value */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Mailing list with given id does not exist */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "toType": "ExceptionTO",
                     *       "exceptionClassName": "java.lang.RuntimeException",
                     *       "originalMessage": "de.maxmomentum.extern.exception.ResourceNotFoundException: mailinglist not found (ext id 1.368.474.800)",
                     *       "httpStatusCode": "500",
                     *       "userMessage": "Bei der Verarbeitung der Anfrage ist ein Fehler aufgetreten.",
                     *       "stackTrace": "java.lang.RuntimeException: de",
                     *       "serverInfo": "Live-System (Version 1.5-31, Serverzeit 2024-04-12 13:34:38, 51 active users)",
                     *       "requestUuid": null,
                     *       "source": "server",
                     *       "type": "SERVER_GENERAL",
                     *       "code": null
                     *     }
                     */
                    "application/json": components["schemas"]["MlErrorDto"];
                };
            };
        };
    };
    MlDeleteMailinglist: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description List ID */
                mailinglistId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Parameter id contains a non-parsable string value */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Mailinglist with given id does not exist */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "toType": "ExceptionTO",
                     *       "exceptionClassName": "java.lang.RuntimeException",
                     *       "originalMessage": "de.maxmomentum.extern.exception.ResourceNotFoundException: unknown mailinglist (list ext id 16.999.858)",
                     *       "httpStatusCode": "500",
                     *       "userMessage": "Bei der Verarbeitung der Anfrage ist ein Fehler aufgetreten.",
                     *       "stackTrace": "java.lang.RuntimeException: d",
                     *       "serverInfo": "Live-System (Version 1.5-31, Serverzeit 2024-04-12 14:18:15, 45 active users)",
                     *       "requestUuid": null,
                     *       "source": "server",
                     *       "type": "SERVER_GENERAL",
                     *       "code": null
                     *     }
                     */
                    "application/json": components["schemas"]["MlErrorDto"];
                };
            };
        };
    };
    MlFindInternalSubscribers: {
        parameters: {
            query: {
                distributor: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Okay */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MlSherpaDistributorItem"][];
                };
            };
            /** @description Parameter distributor contains a non-parsable string value */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description distributor with given id does not exist */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "toType": "ExceptionTO",
                     *       "exceptionClassName": "java.lang.RuntimeException",
                     *       "originalMessage": "java.lang.IllegalStateException: com.proximity.gp.server.common.exception.ObjectNotAccessibleException: cannot find owner (distributor id 5.163.000)",
                     *       "httpStatusCode": "500",
                     *       "userMessage": "Bei der Verarbeitung der Anfrage ist ein Fehler aufgetreten.",
                     *       "stackTrace": "java.lang.RuntimeException...",
                     *       "serverInfo": "Live-System (Version 1.5-31, Serverzeit 2024-04-12 14:34:58, 45 active users)",
                     *       "requestUuid": null,
                     *       "source": "server",
                     *       "type": "SERVER_GENERAL",
                     *       "code": null
                     *     }
                     */
                    "application/json": components["schemas"]["MlErrorDto"];
                };
            };
        };
    };
    MlFindBannedEmails: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Okay */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    SamlFindNewUsersByDate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Find new user params */
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: date-time
                     * @example 2021-01-27T16:50:37+0100
                     */
                    from: string;
                    /**
                     * Format: date-time
                     * @example 2021-01-28T16:50:37+0100
                     */
                    to: string;
                };
            };
        };
        responses: {
            /** @description List of new users */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SamlNewUser"][];
                };
            };
            /** @description Missing Request Body */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            500: components["responses"]["SamlServerError"];
        };
    };
    SamlGetUsersById: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @example [
                     *       "12345678",
                     *       "12345679"
                     *     ]
                     */
                    partyIdList: string[];
                };
            };
        };
        responses: {
            /** @description List of new users */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SamlUser"][];
                };
            };
            500: components["responses"]["SamlServerError"];
        };
    };
    SamlFindUsers: {
        parameters: {
            query?: {
                /** @description Max amount of users to return */
                limit?: number;
                /** @description Last user id, used for keyset pagination. */
                after?: string;
                /** @description ISO8601 compliant date. Only list users modified after given date. */
                modified_after?: string;
                /** @description ISO8601 compliant date. Only list users modified before given date. */
                modified_before?: string;
                /** @description Filter users by user ids */
                "include[]"?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Find user response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SamlFindUsersResponse"];
                };
            };
        };
    };
    SamlCreateGuestAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SamlCreateGuestAccountDto"];
            };
        };
        responses: {
            /**
             * @description An existing party record was found and marked as a guest. It keeps
             *     its id.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SamlUser"];
                };
            };
            /** @description No party record existed. It was created and marked as a guest. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SamlUser"];
                };
            };
            /**
             * @description Invalid input: missing required fields, implausible values, unknown
             *     division.
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SamlError"];
                };
            };
            /** @description The calling certificate is not permitted to use this endpoint. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SamlError"];
                };
            };
            /**
             * @description The person already has access to the Grünes Netz and cannot become a
             *     guest.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SamlError"];
                };
            };
            /**
             * @description Several party records match the given data and cannot be resolved
             *     automatically. Neither one of them is picked nor a new record
             *     created; the case needs manual clarification.
             */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SamlError"];
                };
            };
            500: components["responses"]["SamlServerError"];
        };
    };
    SamlRevokeGuestAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Sherpa user id of the guest account */
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The guest marker was removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The calling certificate is not permitted to use this endpoint. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SamlError"];
                };
            };
            /** @description No party record with a guest marker exists for the given id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SamlError"];
                };
            };
            500: components["responses"]["SamlServerError"];
        };
    };
    SamlRenewGuestAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Sherpa user id of the guest account */
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The guest marker was extended. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SamlUser"];
                };
            };
            /** @description The calling certificate is not permitted to use this endpoint. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SamlError"];
                };
            };
            /** @description No party record with a guest marker exists for the given id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SamlError"];
                };
            };
            /**
             * @description The extension would exceed the maximum duration of the guest marker.
             *     The account keeps its current expiry.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SamlError"];
                };
            };
            500: components["responses"]["SamlServerError"];
        };
    };
    GnGetProfileIds: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of user profile ids */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    GnGetProfiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description List of profile ids */
                    profileIds?: string[];
                    /** @description List of user ids */
                    userIds?: string[];
                };
            };
        };
        responses: {
            /** @description List of user profiles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GnProfile"][];
                };
            };
            422: components["responses"]["GnValidationFailed"];
        };
    };
    GnCreateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GnCreateProfileDto"];
            };
        };
        responses: {
            /** @description Created user profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GnProfile"];
                };
            };
            422: components["responses"]["GnValidationFailed"];
        };
    };
    GnDeleteProfiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description List of profile ids */
                    profileIds?: string[];
                    /** @description List of user ids */
                    userIds?: string[];
                };
            };
        };
        responses: {
            /** @description List of deleted user profiles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GnDeletedProfileDto"][];
                };
            };
            422: components["responses"]["GnValidationFailed"];
        };
    };
    GnUpdateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User profile id */
                profileId: components["parameters"]["GnProfileId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GnUpdateProfileDto"];
            };
        };
        responses: {
            /** @description Updated user profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GnProfile"];
                };
            };
            422: components["responses"]["GnValidationFailed"];
        };
    };
    GnGetProfileFormValues: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User profile id */
                profileId: components["parameters"]["GnProfileId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User profile form values */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GnProfileFormValues"];
                };
            };
            404: components["responses"]["GnNotFound"];
        };
    };
    GnGetDivision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Division ID */
                divisionKey: components["schemas"]["DivisionKey"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Division */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnyDivision"];
                };
            };
            404: components["responses"]["GnNotFound"];
        };
    };
    GnFindTags: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of Tags */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GnTag"][];
                };
            };
        };
    };
    GnFindInterests: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of Tags */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GnTag"][];
                };
            };
        };
    };
    GnFindSkills: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of Tags */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GnTag"][];
                };
            };
        };
    };
}
